# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(choices=[(None, 'выберите пожалуйста'), (True, 'Да'), (False, 'Нет')])),
                ('drink', models.IntegerField(choices=[(None, 'выберите пожалуйста'), (0, 'Чай'), (1, 'Кофе'), (2, 'Сок')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partymaker.User'),
        ),
    ]
